<?xml version="1.0" encoding="utf-8"?><Database Name="MailSenderDb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MailSenderDb.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MailSender.Properties.Settings" SettingsPropertyName="MailSenderDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Email" Member="Email">
    <Type Name="Email">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Member="Email1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>